name: 'Clikd Release Action'
description: 'Semantic releases with AI changelogs. Creates a release PR with auto-bumped versions from conventional commits.'
author: 'Clikd Inc.'

branding:
  icon: 'package'
  color: 'purple'

inputs:
  version:
    description: 'Version of clikd to install (e.g., "0.5.0" or "latest")'
    required: false
    default: 'latest'

  bump:
    description: 'Version bump type: major, minor, patch, auto (default: auto - determined by conventional commits)'
    required: false
    default: 'auto'

  projects:
    description: 'Per-project version bumps as comma-separated list (e.g., "gate:major,rig:minor,core:patch")'
    required: false
    default: ''

  anthropic-api-key:
    description: 'Anthropic API key for AI-powered changelog generation (optional)'
    required: false
    default: ''

  github-token:
    description: 'GitHub token for creating PRs and pushing branches'
    required: false
    default: ${{ github.token }}

  working-directory:
    description: 'Working directory for the release process'
    required: false
    default: '.'

  dry-run:
    description: 'Run release process without pushing or creating PR (for testing)'
    required: false
    default: 'false'

  git-user-name:
    description: 'Git user name for commits'
    required: false
    default: 'github-actions[bot]'

  git-user-email:
    description: 'Git user email for commits'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'

outputs:
  pr-created:
    description: 'Whether a release PR was created ("true" or "false")'
    value: ${{ steps.release.outputs.pr_created }}

  pr-url:
    description: 'URL of the created pull request'
    value: ${{ steps.release.outputs.pr_url }}

  pr-number:
    description: 'Number of the created pull request'
    value: ${{ steps.release.outputs.pr_number }}

  releases:
    description: 'JSON array of packages to be released with name, old_version, new_version'
    value: ${{ steps.release.outputs.releases }}

  release-count:
    description: 'Number of packages in the release'
    value: ${{ steps.release.outputs.release_count }}

runs:
  using: 'composite'
  steps:
    - name: Setup Git identity
      shell: bash
      env:
        GIT_USER_NAME: ${{ inputs.git-user-name }}
        GIT_USER_EMAIL: ${{ inputs.git-user-email }}
      run: |
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"

    - name: Install clikd
      shell: bash
      env:
        CLIKD_VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -euo pipefail

        echo "::group::Installing clikd"

        if [ "$CLIKD_VERSION" = "latest" ]; then
          echo "Fetching latest version..."
          CLIKD_VERSION=$(curl -sL \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/clikd-inc/cli/releases/latest" | \
            grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/^v//')
        fi

        echo "Installing clikd v${CLIKD_VERSION}"

        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        case "$ARCH" in
          x86_64) ARCH="x86_64" ;;
          aarch64|arm64) ARCH="aarch64" ;;
          *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac

        case "$OS" in
          linux) TARGET="${ARCH}-unknown-linux-gnu" ;;
          darwin) TARGET="${ARCH}-apple-darwin" ;;
          *) echo "Unsupported OS: $OS"; exit 1 ;;
        esac

        DOWNLOAD_URL="https://github.com/clikd-inc/cli/releases/download/v${CLIKD_VERSION}/clikd-${TARGET}.tar.xz"

        echo "Downloading from: $DOWNLOAD_URL"

        curl -sL "$DOWNLOAD_URL" | tar -xJ

        sudo mv clikd /usr/local/bin/
        chmod +x /usr/local/bin/clikd

        echo "Installed clikd $(clikd --version)"
        echo "::endgroup::"

    - name: Run clikd release prepare
      id: release
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WORKING_DIR: ${{ inputs.working-directory }}
        BUMP_TYPE: ${{ inputs.bump }}
        PROJECTS: ${{ inputs.projects }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        set -euo pipefail

        cd "$WORKING_DIR"

        echo "::group::Running clikd release prepare"

        # Bump type as positional argument (auto is default, so skip it)
        BUMP_ARG=""
        if [ -n "$BUMP_TYPE" ] && [ "$BUMP_TYPE" != "auto" ]; then
          BUMP_ARG="$BUMP_TYPE"
        fi

        ARGS="--ci"

        if [ -n "$PROJECTS" ]; then
          IFS=',' read -ra PROJECT_ARRAY <<< "$PROJECTS"
          for proj in "${PROJECT_ARRAY[@]}"; do
            ARGS="$ARGS --project $proj"
          done
        fi

        echo "Executing: clikd release prepare $BUMP_ARG $ARGS"

        if [ "$DRY_RUN" = "true" ]; then
          echo "Dry-run mode: would execute 'clikd release prepare $ARGS'"
          echo "pr_created=false" >> "$GITHUB_OUTPUT"
          echo "pr_url=" >> "$GITHUB_OUTPUT"
          echo "pr_number=" >> "$GITHUB_OUTPUT"
          echo "releases=[]" >> "$GITHUB_OUTPUT"
          echo "release_count=0" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"
          exit 0
        fi

        OUTPUT=$(clikd release prepare $BUMP_ARG $ARGS 2>&1) || {
          EXIT_CODE=$?
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "no projects needed version bumps"; then
            echo "No releases needed"
            echo "pr_created=false" >> "$GITHUB_OUTPUT"
            echo "pr_url=" >> "$GITHUB_OUTPUT"
            echo "pr_number=" >> "$GITHUB_OUTPUT"
            echo "releases=[]" >> "$GITHUB_OUTPUT"
            echo "release_count=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          exit $EXIT_CODE
        }

        echo "$OUTPUT"

        echo "::endgroup::"

        PR_URL=$(echo "$OUTPUT" | grep -oP 'pull request created: \K.*' || echo "")

        if [ -n "$PR_URL" ]; then
          echo "pr_created=true" >> "$GITHUB_OUTPUT"
          echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"

          PR_NUMBER=$(echo "$PR_URL" | grep -oP '/pull/\K\d+' || echo "")
          echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"

          RELEASE_COUNT=$(echo "$OUTPUT" | grep -oP 'prepared \K\d+' || echo "0")
          echo "release_count=$RELEASE_COUNT" >> "$GITHUB_OUTPUT"

          RELEASES=$(echo "$OUTPUT" | grep -E '^\s+\S+:.*->.*\(' | while read -r line; do
            NAME=$(echo "$line" | awk -F: '{print $1}' | xargs)
            VERSIONS=$(echo "$line" | grep -oP '\d+\.\d+\.\d+' | head -2)
            OLD_VERSION=$(echo "$VERSIONS" | head -1)
            NEW_VERSION=$(echo "$VERSIONS" | tail -1)
            echo "{\"name\":\"$NAME\",\"old_version\":\"$OLD_VERSION\",\"new_version\":\"$NEW_VERSION\"}"
          done | jq -s '.' 2>/dev/null || echo "[]")

          echo "releases=$RELEASES" >> "$GITHUB_OUTPUT"

          echo "::notice::Created release PR: $PR_URL"
        else
          echo "pr_created=false" >> "$GITHUB_OUTPUT"
          echo "pr_url=" >> "$GITHUB_OUTPUT"
          echo "pr_number=" >> "$GITHUB_OUTPUT"
          echo "releases=[]" >> "$GITHUB_OUTPUT"
          echo "release_count=0" >> "$GITHUB_OUTPUT"
        fi
